version: "3"

volumes:
  database_data:
  bundle_path:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: beetrack-v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis

  beetrack-v2:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    volumes:
      - .:/beetrack-v2
      - bundle_path:/bundle
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/beetrack-v2
      - bundle_path:/bundle
    env_file:
      - .env
    depends_on:
      - db
      - redis