default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beetrack_v2_development
  host: db
  username: postgres
  password: postgres

test:
  <<: *default
  database: beetrack_v2_test
  host: db 
  username: postgres
  password: postgres

production:
  <<: *default
  database: beetrack_v2_production
